services:
  docs:
    image: photographer_booking_app_local_docs
    container_name: photographer_booking_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./photographer_booking_app:/app/photographer_booking_app:z
    ports:
      - '9000:9000'
    command: /start-docs
