# Generated by Django 4.2.13 on 2024-06-05 19:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(verbose_name='Who am I?')),
                ('display_picture', models.ImageField(default='/photographer/display_pictures/default.jpg', upload_to='photographer/display_pictures/')),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='Phone')),
                ('Fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fees/hour')),
            ],
        ),
    ]
