# Generated by Django 4.2.13 on 2024-06-08 18:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import photographer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(verbose_name='Who am I?')),
                ('display_picture', models.ImageField(default='/photographer/display_pictures/default.jpg', upload_to='photographer/display_pictures/')),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='Phone')),
                ('Fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fees/hour')),
                ('Category', models.CharField(blank=True, choices=[('Adventure Photography', 'Adventure Photography'), ('Aerial Photography', 'Aerial Photography'), ('Astro Photography', 'Astro Photography'), ('Automotive Photography', 'Automotive Photography'), ('Commercial Photography', 'Commercial Photography'), ('Documentary Photography', 'Documentary Photography'), ('Event Photography', 'Event Photography'), ('Fashion Photography', 'Fashion Photography'), ('Fine Art Photography', 'Fine Art Photography'), ('Food Photography', 'Food Photography'), ('Industrial Photography', 'Industrial Photography'), ('Landscape Photography', 'Landscape Photography'), ('Medical Photography', 'Medical Photography'), ('Pet Photography', 'Pet Photography'), ('Photojournalist', 'Photojournalist'), ('Portrait Photography', 'Portrait Photography'), ('Product Photography', 'Product Photography'), ('Real Estate Photography', 'Real Estate Photography'), ('Scientific Photography', 'Scientific Photography'), ('Sports Photography', 'Sports Photography'), ('Stock Photography', 'Stock Photography'), ('Street Photography', 'Street Photography'), ('Travel Photography', 'Travel Photography'), ('War Photography', 'War Photography'), ('Wedding Photography', 'Wedding Photography'), ('Wildlife Photography', 'Wildlife Photography')], max_length=1000, null=True, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_images', models.ImageField(default='uploads/default.jpg', upload_to="uploads/portfolio_gallery/")),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photographer.photographer')),
            ],
        ),
    ]
