# Generated by Django 5.0.6 on 2024-06-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='Fees',
            new_name='fees',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photographer',
        ),
        migrations.AddField(
            model_name='photographer',
            name='portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='photographer.portfolio', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='Phone_Number',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
    ]
