# Generated by Django 4.2.13 on 2024-06-08 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBaseModel',
            fields=[
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_made_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCall',
            fields=[
                ('bookbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.bookbasemodel')),
                ('booked_for', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='photographer.photographer')),
            ],
            bases=('booking.bookbasemodel',),
        ),
        migrations.CreateModel(
            name='BookASession',
            fields=[
                ('bookbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.bookbasemodel')),
                ('booked_For', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='photographer.photographer')),
            ],
            bases=('booking.bookbasemodel',),
        ),
    ]
